homework_arrays
VovanShaitan/ru-study-ruby pull request #1
Opened 2022-09-29 16:29 UTC by VovanShaitan

Element replacement and binary search in arrays are implemented

2022-09-29 19:11 UTC, NickelGit requested changes

2022-09-29 19:11 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        new_arr = array.map { |value| value >=0 ? array.max : value}
"В рамках задания нельзя использовать стандартные функции для поиска максимума и поиска элемента в массиве. Их нужно реализовать самому."

Напиши пожалуйста свой метод поиска максимума.
Так же зачем нам на каждой итерации заново искать максимальное значение в массиве? 
Эффективнее будет записать максимальное значение в переменную и в тернарном операторе использовать эту переменную.

Создание переменной `new_arr` избыточно, дальше мы ее нигде не используем, можно ограничиться просто методом `.map` он вернет новый массив как результат работы метода.

2022-09-29 19:11 UTC, NickelGit commented on test/exercise/arrays/solution.rb
>        def search(_array, _query)
по соглашению нижнее подчеркивание означает неиспользуемые в методе аргументы. Удали пжлст нижнее подчеркивание в начале названия аргументов.

2022-09-29 19:11 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +            return -1
вложенность ухудшает читаемость, лучше представить это в виде нескольких guard clause
https://anthonygharvey.com/guard-clauses-vs-nested-conditionals

И вместо цикла лучше использовать рекурсивный вызов функции с аргументами по умолчанию для первого вызова
https://medium.com/@sologoubalex/parameters-with-default-values-in-ruby-74cd0e830681

2022-10-02 15:15 UTC, VovanShaitan commented on test/exercise/arrays/solution.rb
> +        new_arr = array.map { |value| value >=0 ? array.max : value}
Все исправления внес в коммит
https://github.com/VovanShaitan/ru-study-ruby/pull/1/commits/63ea486827430dbea3e7e3cb3e112aba6fe4b39f
С ситуацией корректирования PR столкнулся впервые. Надеюсь, что все делаю верно

2022-10-03 05:32 UTC, NickelGit requested changes

2022-10-03 05:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
вынеси пжлст поиск максимума в отдельный метод.

2022-10-03 05:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return -1 if min > max
давай перенесем этот guard clause в самый верх. А так же добавим в него проверки что элемент который мы ищем находится в пределах наших границ поиска (т.е. что элемент который мы ищем больше самого маленького и меньше самого большого элемента в границах поиска). Т.к. бинарный поиск возможен только в отсортированных массивах мы исходим из того что наш массив всегда отсортирован по возрастанию.

2022-10-03 05:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return mid if (array[mid] == query)
давай перенесем эту проверку над рекурсивным вызовом метода, т.к. если мы уже нашли элемент то нам нет необходимости проводить те проверки.
И для упрощениях чтения кода добавь пжлст пустую строку после всех оставшихся `return`

2022-10-03 05:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return search(array, query, mid+1, max) if (array[mid] < query)
Давай представим это в виде тернарной операции, и перенесем в самый конец метода. Тогда нам тут return не понадобится, т.к. результат работы последней строки в методе возвращается как результат его работы.

2022-10-03 05:33 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        new_arr = array.map { |value| value >=0 ? array.max : value}
Да, в плане корректировки все верно. Надо просто внести изменения в код и пукнуть эти новые коммиты.

2022-10-03 09:40 UTC, VovanShaitan commented on test/exercise/arrays/solution.rb
> +        return mid if (array[mid] == query)
Вот тут с пустыми строками не совсем понял, но на всякий случай вжмакнул после каждого return`а.

2022-10-03 12:45 UTC, NickelGit requested changes

2022-10-03 12:45 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
перепиши пжлст этот блок с использованием `.each` 

И еще надо убрать `skip` из тестов и прогнать литер и тесты. В readme описано как это можно сделать.

2022-10-06 12:18 UTC, VovanShaitan commented on test/exercise/arrays/solution.rb
> +        end
Линтер в методе replace предлагает array.map { |value| value.positive? ? max : value } 
вместо array.map { |value| value > 0 ? max : value }. Оставил как есть, но метод positive? запомнил.

Тесты выдают следующее:

  1) Failure:
Exercise::ArraysTest#test_replace [/apps/study/test/exercise/arrays/test.rb:10]:
Expected false to be truthy.

8 runs, 8 assertions, 1 failures, 0 errors, 6 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1)
/bundle_cache/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)

Уже глаз дергается, не знаю как пофиксить. Подскажи, пожалуйста. Задание простое, а туплю безбожно и стопорюсь на ровном месте, хотя финиш перед глазами.

2022-10-06 12:30 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
1) лучше оставить `.positive?`, литер плохого не посоветует) Если он конечно правильно настроен)
2) Раз тесты не проходят, значит в методе что то не так) а раз падает тест `test_replace` значит неправильно работает метод `replace` (или методы используемые внутри метода `replace`).  Посмотри что и как проверят этот тест, и потом например можно вывести в консоль что возвращает твой метод и сравнить с тем что ожидает тест.

2022-10-06 16:50 UTC, merged